service: api
frameworkVersion: "2"

package:
  individually: true
  include:
    - "./google-service-credentials.json"

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    apiKeys:
      - amplifyKey
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource:
            - !Join
              - ""
              - - "arn:aws:s3:::"
                - ${env:S3_BUCKET}
                - "/*"

functions:
  getLanguage:
    handler: src/get-language.handler

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "./google-service-credentials.json"
      S3_BUCKET: ${env:S3_BUCKET}
    events:
      - http:
          path: language
          method: get
          cors: true
          private: true
          request:
            parameters:
              querystrings:
                uri: false

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
