service: api
frameworkVersion: "2"

custom:
  webpack:
    webpackConfig: "./web"
package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  getLanguage:
    handler: src/get-language.handler
    package:
      patterns:
        - "*.json"
        - google-service-credentials.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "./google-service-credentials.json"
    events:
      - http:
          path: language
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                uri: false

plugins:
  - serverless-plugin-typescript
  - serverless-offline
