service: api
frameworkVersion: "2"

package:
  individually: true
  include:
    - "./google-service-credentials.json"

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    apiKeys:
      - amplifyKey

functions:
  getLanguage:
    handler: src/get-language.handler
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "./google-service-credentials.json"
    events:
      - http:
          path: language
          method: get
          cors: true
          private: true
          request:
            parameters:
              querystrings:
                uri: false

plugins:
  - serverless-offline
  - serverless-plugin-typescript
